# Generated by Django 2.2.4 on 2024-07-03 19:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_direccion_etiqueta'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Persona',
            new_name='Personal',
        ),
    ]
