# Generated by Django 2.2.4 on 2024-07-03 20:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0004_auto_20240703_1424'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('titulo', models.CharField(max_length=255)),
                ('fecha_creacion', models.DateTimeField()),
                ('fecha_cierre', models.DateTimeField()),
                ('etiqueta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Etiqueta')),
                ('presentado_en', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Direccion')),
                ('presentado_por', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Personal')),
                ('resuelto_por', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('contenido', models.TextField()),
                ('fecha_creacion', models.DateTimeField()),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Personal')),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Ticket')),
            ],
        ),
    ]
