# Generated by Django 2.2.4 on 2024-07-09 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_auto_20240709_1507'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='fecha_cierre',
            field=models.DateTimeField(null=True),
        ),
    ]
