# Generated by Django 2.2.4 on 2024-07-10 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_auto_20240710_1418'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comentario',
            name='titulo',
        ),
        migrations.AlterField(
            model_name='comentario',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
