# Generated by Django 5.0.7 on 2024-07-15 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='personal',
            options={'verbose_name': 'personal', 'verbose_name_plural': 'personal'},
        ),
        migrations.AlterField(
            model_name='ticket',
            name='fecha_cierre',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
